package com.phkcyber.fireeyeautomation;

public enum KEY {
    SRC_IP,
    SRC_PORT,
    SRC_HOST,
    DST_IP,
    DST_PORT,
    DST_HOST,
    HOST_OS,
    HOST_AGENT,
    HOST_DOMAIN,
    HOST_HOSTNAME,
    HOST_TIMEZONE,
    HOST_LAST,
    INFECTION_NAME,
    INFECTION_TYPE,
    MALWARE_NAME,
    MALWARE_TYPE,
    CNC_NAME,
    CNC_TYPE,
    CNC_URL,
    CNC_DATA,
    MALWARE_DATA,
    ALERT_URL,
    OCCURRED,
    MATCHED,
    SENSOR,
    USERNAME,
    PROCESS,
    PROCESS_PATH,
    AGENT_ID,
    AGENT_VERSION,
    ACTION,
    ANALYSIS
}
